### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by Giapa** [AdopseTeam/IMDB#12]
Create a Wiki page containing information about the project

**Comment by savvas23** [comment]
Added Roles wikipage

**Comment by Giapa** [comment]
@savvas23 should we add more roles? Devops would be a nice role to have on the team. I think you should also add yourself on another role. We will also need some QA roles.

**Comment by savvas23** [comment]
> @savvas23 should we add more roles? Devops would be a nice role to have on the team. I think you should also add yourself on another role. We will also need some QA roles.

More detailed roles will be added to the project as it keeps getting developed. As you said some extra roles could be "Devops","QA","User Evaluation","Testing".

**Comment by savvas23** [comment]
Added Functional Requirements wikipage
