### ISSUE TITLE
Wrong ID to Models from API Calls

### ISSUE THREAD

**Issue by savvas23** [AdopseTeam/IMDB#47]
IDs in the Models are not correct when they are assigned by loop counter. They are standard IDs that correspond to the movie/series/actor IMDB profile. A new field must be created named ActorId/MovieID/SeriesID that is equal to the respone that comes from the API.

**Comment by Giapa** [comment]
The incremental IDs are used as a unique ID for the database.  The IDs from the API are missing from the model which is covered on another issue.
